name: Compilar Aplicación Android

on:
  repository_dispatch:
    types: [solicitud-compilacion]

jobs:
  compilar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Obtener código
        uses: actions/checkout@v4
        
      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      
      - name: Instalar herramientas
        run: |
          npm install -g @capacitor/cli
          npx cap init --app-name "${{ github.event.client_payload.nombre_app }}" --app-id "${{ github.event.client_payload.id_app }}"
          npx cap add android
      
      - name: Crear Android App Bundle
        run: |
          cd android
          ./gradlew bundleRelease
      
      - name: Subir resultados
        uses: actions/upload-artifact@v3
        with:
          name: app-android
          path: android/app/build/outputs/bundle/release/*.aab
