name: Compilar Aplicación Android

on: 
  workflow_dispatch:   # ¡Este es el cambio clave!
    inputs:
      nombre_app:
        description: 'Nombre de la aplicación'
        required: true
        default: 'MiAppTest'
      id_app:
        description: 'ID de la aplicación (ej: com.mi.app)'
        required: true
        default: 'com.test.app'

jobs:
  compilar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Obtener código
        uses: actions/checkout@v4
        
      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      
      - name: Instalar herramientas
        run: |
          npm install -g @capacitor/cli
          npx cap init --app-name "${{ inputs.nombre_app }}" --app-id "${{ inputs.id_app }}"
          npx cap add android
      
      - name: Crear Android App Bundle
        run: |
          cd android
          ./gradlew bundleRelease
      
      - name: Subir resultados
        uses: actions/upload-artifact@v3
        with:
          name: app-android
          path: android/app/build/outputs/bundle/release/*.aab
